---
title: "CDS 101 Disney Project"
author: "Somto, Jacob, Angela "
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
--- 


```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(broom)
disney <- read.csv("disney_plus_titles.csv")


```


```{r}

### Shows Each Column with examples
glimpse(disney)

### Shows each Variable

summary(disney)
```

2.)
```{r}
### Converts the release year variable from character to a numeric value
disney <- disney %>%
  mutate(release_year = as.numeric(release_year))
```

```{r}
### Converts the duration variable from character to a numeric value
disney <- disney %>%
  mutate(duration_num = parse_number(duration))
```

```{r}
### Transforms the ratings and listed_in variables into factors which makes them categorical
disney <- disney %>%
  mutate(
    rating = as.factor(rating),
    listed_in = as.factor(listed_in)
  )
```

3.) Exploring Relationships: 
```{r}
#Creates a scatter plot looking at the relationship between the release year 
#and the duration of the movie to see if there is any correlation between the two.
ggplot(disney, aes(x = release_year, y = duration_num)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm") +
  labs(title = "Duration vs Year of Release")
```

ii.)
```{r}
# Adds a new column named period which splits release years into different periods
#of time being 25 years apart from each other. 
disney <- disney %>%
  mutate(period = cut(
    release_year,
    breaks = c(1900, 1925, 1950, 1975, 2000, 2025),
    labels = c("1900–1924", "1925–1949", "1950–1974", "1975–1999", "2000–2024"),
    right = FALSE
  ))
```

```{r}
# Creates a new data set looking at the amount of movies spread based on 
# two different factors.
# The factors being time period and rating of the movie.
# For example, This just gives the total amount of movies for rated G during 
# the years of 2000-2024
top_ratings <- disney %>%
  count(period, rating, sort = TRUE) %>%
  group_by(period) %>%
  slice_max(n, n = 5) %>%
  ungroup()
```

```{r}
#New dataset making sure all the values match from top_ratings using the semi_join 
#function
ratings_top <- disney %>%
  semi_join(top_ratings, by = c("period", "rating"))
```

```{r}
#Creates a bar plot looking at the distribution of age rating throughout the years.
ratings_top %>%
  count(period, release_year, rating) %>%
  ggplot(aes(x = release_year, y = n, fill = rating)) +
  geom_col(position = "fill") +
  facet_wrap(~ period, scales = "free_x") +
  labs(
    title = "Rating Distribution Over Time (Top 5 Ratings per 25-Year Interval)",
    x = "Year of Release",
    y = "Proportion",
    fill = "Rating"
  )
```

iii.) 
```{r}
# Creates a new data set with new rows based on the listed_in Variable. 
# This new data set creates new rows based on the different genres of each movie. 
# For example the first movie in the data set 
# "Duck the Halls: A Mickey Mouse Christmas Special" 
# is split into two different two rows with one having animation and the other being family. 
# Not all rows will be split, but all rows will keep the other same data 
# such as rating and release year.
disney_genre <- disney %>%
  separate_rows(listed_in, sep = ", ") %>%
  mutate(listed_in = as.factor(listed_in))
```

```{r}
# This does the same thing as earlier, adding a new column named period.
# This adds a column based on the release date of the movie, 
# being 25 years apart from each other. 
disney_genre <- disney_genre %>%
  mutate(period = cut(
    release_year,
    breaks = c(1900, 1925, 1950, 1975, 2000, 2025),
    labels = c("1900–1924", "1925–1949", "1950–1974", "1975–1999", "2000–2024"),
    right = FALSE
  ))
```

```{r}
# Does the same thing earlier and counts the total amount of movies 
# based on rating sorted year
top_genres <- disney_genre %>%
  count(period, listed_in, sort = TRUE) %>%
  group_by(period) %>%
  slice_max(n, n = 5) %>%
  ungroup()
```

```{r}
#New dataset making sure all the values match from disney_genre using the semi_join 
#function
disney_top <- disney_genre %>%
  semi_join(top_genres, by = c("period", "listed_in"))
```


```{r}
# Creates multiple bar plots looking at the top 5 genres 
# at a with a range of 25 years. 
# Shows the relationship between genres and intervalss of release.
disney_top %>%
  count(period, release_year, listed_in) %>%
  ggplot(aes(x = release_year, y = n, fill = listed_in)) +
  geom_col() +
  facet_wrap(~ period, scales = "free_x") +
  labs(
    title = "Top 5 Genres per 25-Year Interval",
    x = "Year of Release",
    y = "Number of Titles",
    fill = "Genre"
  )
```

iv.) 
```{r}
#Separates the genres in the table into one individual rating, instead of two or more.
ratings_top <- disney %>%
  separate_rows(listed_in, sep = ", ") %>%
  mutate(listed_in = as.factor(listed_in))
```

```{r}
#Identifies the top 5 genres
ratings_top <- disney_genre %>%
  count(listed_in, sort = TRUE) %>%
  slice_max(n, n = 5) %>%
  pull(listed_in)
```

```{r}
#Filters the data set to only the top 5 genres. 
ratings_top <- disney_genre %>%
  filter(listed_in %in% ratings_top)

```

```{r}
#Makes bar chart to see relationship between the genre and rating. 
ratings_top %>%
  count(listed_in, rating) %>%
  ggplot(aes(x = listed_in, y = n, fill = rating)) +
  geom_col() +
  labs(
    title = "Relationship Between Genre and Rating (Top 5 Genres)",
    x = "Genre",
    y = "Number of Titles",
    fill = "Rating"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

4.) 
```{r results = "hide"}
# fits the duration and release year into a linear regression 
# model and provides statistics such as p values, estimates,
# r.squared, and sigma
model_duration <- lm(duration_num ~ release_year, data = disney)
tidy(model_duration)
glance(model_duration)
```

```{r results = "hide"}
# Fits the rating year into a linear regression model 
# based on the release years and provides the same statistics
model_rating <- lm(as.numeric(rating) ~ release_year, data = disney)
tidy(model_rating)
```

5.) 
```{r results = "hide"}
# Does the same thing as the other code chunks, basically asking 
# How release year, rating, and genre impact the movie duration
model_multi <- lm(duration_num ~ release_year + rating + listed_in, data = disney)
tidy(model_multi)
glance(model_multi)
```
 
```{r results = "hide"}
# This creates a linear regression model looking and how 
# only release year and rating predict duration. 
# and provides statistics like previous code chunks
model_multi1 <- lm(duration_num ~ release_year + rating, data = disney)
tidy(model_multi)
glance(model_multi)
```


6.) 
```{r}
# Adds  the pred and resid variables from the previous
# code chunks to a new dataset named disney_pred
disney_pred <- disney %>%
  add_predictions(model_multi1, var = "pred") %>%
  add_residuals(model_multi1, var = "resid")
```

7.) 
```{r}
# Plots residual vs predicted durations 
# x= predicted duration 
# y = resisuals (actual - predicted)
ggplot(disney_pred, aes(x = pred, y = resid)) +
  geom_point(alpha = 0.4) +
  geom_hline(yintercept = 0, color = "red")
```

```{r}
# Plots predicted vs actual duration
# X is the predicted duration
# y is the acutal duration of the movie
ggplot(disney_pred, aes(x = pred, y = duration_num)) +
  geom_point(alpha = 0.4) +
  geom_abline(color = "blue")
```

